# Generated by Django 3.1.7 on 2021-06-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('manager_id', models.CharField(max_length=40)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('t_price', models.CharField(max_length=40)),
            ],
        ),
    ]
